server:
  port: ${PORT:${SERVER_PORT:0}}

spring:
  application:
    name: api-movie
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/movie-dev?createDatabaseIfNotExist=true
    username: usr-movie
    password: pwd-movie
  jpa:
    database-platform: org.hibernate.dialect.MySQL57Dialect
    hibernate.ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: UTC
  jackson:
    serialization:
      write_dates_as_timestamps: false
    date-format: yyyy-MM-dd
    
eureka:
   instance:
     hostname: localhost
     instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
   client:
      registerWithEureka: true
      fetchRegistry: true
      serviceUrl:
        defaultZone: http://localhost:8761/eureka/
